# ??? ?? spring-batch-job-names? ???? args ??? ??? ???
# --spring.batch.job.name=helloJob  // ?
# --job.name=helloJob // ?

spring:
  batch:
    job:
      names: ${job.name:NONE}
    initialize-schema:
